### ISSUE TITLE
assignment 4 Reversing string

### ISSUE THREAD

**Issue by 58bit23** [vtcbca/basic-programming-45bit23#2]
How can we access the strings?

**Comment by 45bit23** [comment]
you can access a string by referring to its index number inside square brackets [] .

**Comment by 58bit23** [comment]
Can you explain using a example

**Comment by 45bit23** [comment]
For example, if char *ptr = "hello";, *(ptr + 1) would give you e, the second character of the string.

**Comment by 58bit23** [comment]
Ok, Can you try with the word 'Umrakh'.

**Comment by 45bit23** [comment]
yeah sure

**Comment by 58bit23** [comment]
Ok then give the solution for 'Umrakh'.

**Comment by 45bit23** [comment]
# Defining a string that contains the word 'Umrakh'
my_string = "The word Umrakh is used as an example in this string."

# Accessing the string
if "Umrakh" in my_string:
    print("The word 'Umrakh' was found in the string.")
else:
    print("The word 'Umrakh' was not found in the string.")

**Comment by 58bit23** [comment]
Ok I understood how to access the string

**Comment by 58bit23** [comment]
Thank you @45bit23 for your positive and effective response.

**Comment by 45bit23** [comment]
That's Great

**Comment by 45bit23** [comment]
@58bit23 Most Welcome
