### ISSUE TITLE
Assignment-8 : Pattern of Alphabets

### ISSUE THREAD

**Issue by 52bit23** [vtcbca/basic-programming-45bit23#3]
How are spaces added to make the triangle shape?

**Comment by 45bit23** [comment]
Spaces are printed first using " " * (n - i), reducing as the rows increase.

**Comment by 52bit23** [comment]
How do you stop the program from throwing an error for invalid input?

**Comment by 45bit23** [comment]
By using a try-except block to handle non-integer inputs.

**Comment by 52bit23** [comment]
How does the program know how many rows to print?

**Comment by 45bit23** [comment]
It takes the number of rows (n) as input from the user.

**Comment by 52bit23** [comment]
Can the program handle more than 26 rows?

**Comment by 45bit23** [comment]
Yes, but it will repeat alphabet patterns.

**Comment by 52bit23** [comment]
What will happen if you input a negative number?

**Comment by 45bit23** [comment]
The program will not print anything since no rows are valid for negative numbers.

**Comment by 52bit23** [comment]
How are reverse letters like B A printed in the same row?

**Comment by 45bit23** [comment]
A loop iterates backward to print letters in reverse order.
